/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WebshopCart {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebshopCheckout {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebshopItem {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLWebshopCartElement extends Components.WebshopCart, HTMLStencilElement {
    }
    var HTMLWebshopCartElement: {
        prototype: HTMLWebshopCartElement;
        new (): HTMLWebshopCartElement;
    };
    interface HTMLWebshopCheckoutElement extends Components.WebshopCheckout, HTMLStencilElement {
    }
    var HTMLWebshopCheckoutElement: {
        prototype: HTMLWebshopCheckoutElement;
        new (): HTMLWebshopCheckoutElement;
    };
    interface HTMLWebshopItemElement extends Components.WebshopItem, HTMLStencilElement {
    }
    var HTMLWebshopItemElement: {
        prototype: HTMLWebshopItemElement;
        new (): HTMLWebshopItemElement;
    };
    interface HTMLElementTagNameMap {
        "webshop-cart": HTMLWebshopCartElement;
        "webshop-checkout": HTMLWebshopCheckoutElement;
        "webshop-item": HTMLWebshopItemElement;
    }
}
declare namespace LocalJSX {
    interface WebshopCart {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebshopCheckout {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebshopItem {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "webshop-cart": WebshopCart;
        "webshop-checkout": WebshopCheckout;
        "webshop-item": WebshopItem;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "webshop-cart": LocalJSX.WebshopCart & JSXBase.HTMLAttributes<HTMLWebshopCartElement>;
            "webshop-checkout": LocalJSX.WebshopCheckout & JSXBase.HTMLAttributes<HTMLWebshopCheckoutElement>;
            "webshop-item": LocalJSX.WebshopItem & JSXBase.HTMLAttributes<HTMLWebshopItemElement>;
        }
    }
}
